### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by 0xLevin** [DWand/SublimeText_apiDoc_autocompletion#1]
I have been in the sublime does 3 installed on the text, but I don't know how to use it. Need to use shortcuts or?

**Comment by DWand** [comment]
Hello, @simman. This plugin adds auto completion suggestions for apiDoc tags (like `@api`, `@apiParam`, `@apiError` and so on). You don't have to learn any special shortcuts to use it. Just install the plugin and it will add new options to your auto completion list.

**Comment by 0xLevin** [comment]
@DWand ,Thank you for your reply, forgive my stupid, I'm going to use it in PHP, but I still don't know how to make it run, if it's convenient for you, if you can do the Gif images to teach me how to use it?

**Comment by DWand** [comment]
I don't know how to make such kind of gif images. But here is a little video example: https://youtu.be/TgaPaPR_UYg
However, there is nothing unusual here - the plugin just extends the standard autocompletion feature in Sublime Text.

**Comment by 0xLevin** [comment]
Thank you very much, look at your Youtube video before they know how to use, should be before I did not restart SublimeText, cause the plug-in for failing to take effect.
