### ISSUE TITLE
Atom editor support

### ISSUE THREAD

**Issue by brunowego** [DWand/SublimeText_apiDoc_autocompletion#2]
Any chance to add create apidoc plugin for Atom? Thanks :+1:

**Comment by DWand** [comment]
Hello, @brunowego. I've never worked with Atom. I don't know how to create plugins for this editor.

**Comment by brunowego** [comment]
I understand. Thanks to reply :+1:

**Comment by DWand** [comment]
@brunowego, do you know how to add auto completion suggestions in Atom? If so, it is possible to implement such thing.
